// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/emu/display/display.go

// Package mock_display is a generated GoMock package.
package mock_display

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockWriter is a mock of Writer interface
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// Clear mocks base method
func (m *MockWriter) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear
func (mr *MockWriterMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockWriter)(nil).Clear))
}

// DisplaySprites mocks base method
func (m *MockWriter) DisplaySprites(x, y uint8, data []uint8) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisplaySprites", x, y, data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DisplaySprites indicates an expected call of DisplaySprites
func (mr *MockWriterMockRecorder) DisplaySprites(x, y, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplaySprites", reflect.TypeOf((*MockWriter)(nil).DisplaySprites), x, y, data)
}
