// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/emu/registers/registers.go

// Package mock_registers is a generated GoMock package.
package mock_registers

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRegisterReaderWriter is a mock of RegisterReaderWriter interface
type MockRegisterReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterReaderWriterMockRecorder
}

// MockRegisterReaderWriterMockRecorder is the mock recorder for MockRegisterReaderWriter
type MockRegisterReaderWriterMockRecorder struct {
	mock *MockRegisterReaderWriter
}

// NewMockRegisterReaderWriter creates a new mock instance
func NewMockRegisterReaderWriter(ctrl *gomock.Controller) *MockRegisterReaderWriter {
	mock := &MockRegisterReaderWriter{ctrl: ctrl}
	mock.recorder = &MockRegisterReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRegisterReaderWriter) EXPECT() *MockRegisterReaderWriterMockRecorder {
	return m.recorder
}

// SetProgramCounter mocks base method
func (m *MockRegisterReaderWriter) SetProgramCounter(address uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProgramCounter", address)
}

// SetProgramCounter indicates an expected call of SetProgramCounter
func (mr *MockRegisterReaderWriterMockRecorder) SetProgramCounter(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProgramCounter", reflect.TypeOf((*MockRegisterReaderWriter)(nil).SetProgramCounter), address)
}

// IncrementProgramCounter mocks base method
func (m *MockRegisterReaderWriter) IncrementProgramCounter(increment uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementProgramCounter", increment)
}

// IncrementProgramCounter indicates an expected call of IncrementProgramCounter
func (mr *MockRegisterReaderWriterMockRecorder) IncrementProgramCounter(increment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementProgramCounter", reflect.TypeOf((*MockRegisterReaderWriter)(nil).IncrementProgramCounter), increment)
}

// PushProgramCounter mocks base method
func (m *MockRegisterReaderWriter) PushProgramCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushProgramCounter")
}

// PushProgramCounter indicates an expected call of PushProgramCounter
func (mr *MockRegisterReaderWriterMockRecorder) PushProgramCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushProgramCounter", reflect.TypeOf((*MockRegisterReaderWriter)(nil).PushProgramCounter))
}

// PopProgramCounter mocks base method
func (m *MockRegisterReaderWriter) PopProgramCounter() uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopProgramCounter")
	ret0, _ := ret[0].(uint16)
	return ret0
}

// PopProgramCounter indicates an expected call of PopProgramCounter
func (mr *MockRegisterReaderWriterMockRecorder) PopProgramCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopProgramCounter", reflect.TypeOf((*MockRegisterReaderWriter)(nil).PopProgramCounter))
}

// GetRegisterValue mocks base method
func (m *MockRegisterReaderWriter) GetRegisterValue(register uint8) uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisterValue", register)
	ret0, _ := ret[0].(uint8)
	return ret0
}

// GetRegisterValue indicates an expected call of GetRegisterValue
func (mr *MockRegisterReaderWriterMockRecorder) GetRegisterValue(register interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisterValue", reflect.TypeOf((*MockRegisterReaderWriter)(nil).GetRegisterValue), register)
}

// SetRegisterValue mocks base method
func (m *MockRegisterReaderWriter) SetRegisterValue(register, value uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRegisterValue", register, value)
}

// SetRegisterValue indicates an expected call of SetRegisterValue
func (mr *MockRegisterReaderWriterMockRecorder) SetRegisterValue(register, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegisterValue", reflect.TypeOf((*MockRegisterReaderWriter)(nil).SetRegisterValue), register, value)
}

// SetRegisterI mocks base method
func (m *MockRegisterReaderWriter) SetRegisterI(value uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRegisterI", value)
}

// SetRegisterI indicates an expected call of SetRegisterI
func (mr *MockRegisterReaderWriterMockRecorder) SetRegisterI(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegisterI", reflect.TypeOf((*MockRegisterReaderWriter)(nil).SetRegisterI), value)
}

// GetRegisterI mocks base method
func (m *MockRegisterReaderWriter) GetRegisterI() uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisterI")
	ret0, _ := ret[0].(uint16)
	return ret0
}

// GetRegisterI indicates an expected call of GetRegisterI
func (mr *MockRegisterReaderWriterMockRecorder) GetRegisterI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisterI", reflect.TypeOf((*MockRegisterReaderWriter)(nil).GetRegisterI))
}

// SetDelayTimer mocks base method
func (m *MockRegisterReaderWriter) SetDelayTimer(value uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDelayTimer", value)
}

// SetDelayTimer indicates an expected call of SetDelayTimer
func (mr *MockRegisterReaderWriterMockRecorder) SetDelayTimer(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDelayTimer", reflect.TypeOf((*MockRegisterReaderWriter)(nil).SetDelayTimer), value)
}

// GetDelayTimer mocks base method
func (m *MockRegisterReaderWriter) GetDelayTimer() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDelayTimer")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// GetDelayTimer indicates an expected call of GetDelayTimer
func (mr *MockRegisterReaderWriterMockRecorder) GetDelayTimer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDelayTimer", reflect.TypeOf((*MockRegisterReaderWriter)(nil).GetDelayTimer))
}

// SetSoundTimer mocks base method
func (m *MockRegisterReaderWriter) SetSoundTimer(value uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSoundTimer", value)
}

// SetSoundTimer indicates an expected call of SetSoundTimer
func (mr *MockRegisterReaderWriterMockRecorder) SetSoundTimer(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSoundTimer", reflect.TypeOf((*MockRegisterReaderWriter)(nil).SetSoundTimer), value)
}

// GetSoundTimer mocks base method
func (m *MockRegisterReaderWriter) GetSoundTimer() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSoundTimer")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// GetSoundTimer indicates an expected call of GetSoundTimer
func (mr *MockRegisterReaderWriterMockRecorder) GetSoundTimer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSoundTimer", reflect.TypeOf((*MockRegisterReaderWriter)(nil).GetSoundTimer))
}
