// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/emu/registers/registers.go

// Package mock_registers is a generated GoMock package.
package mock_registers

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockReaderWriter is a mock of ReaderWriter interface
type MockReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockReaderWriterMockRecorder
}

// MockReaderWriterMockRecorder is the mock recorder for MockReaderWriter
type MockReaderWriterMockRecorder struct {
	mock *MockReaderWriter
}

// NewMockReaderWriter creates a new mock instance
func NewMockReaderWriter(ctrl *gomock.Controller) *MockReaderWriter {
	mock := &MockReaderWriter{ctrl: ctrl}
	mock.recorder = &MockReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReaderWriter) EXPECT() *MockReaderWriterMockRecorder {
	return m.recorder
}

// SetProgramCounter mocks base method
func (m *MockReaderWriter) SetProgramCounter(address uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProgramCounter", address)
}

// SetProgramCounter indicates an expected call of SetProgramCounter
func (mr *MockReaderWriterMockRecorder) SetProgramCounter(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProgramCounter", reflect.TypeOf((*MockReaderWriter)(nil).SetProgramCounter), address)
}

// IncrementProgramCounter mocks base method
func (m *MockReaderWriter) IncrementProgramCounter(increment uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementProgramCounter", increment)
}

// IncrementProgramCounter indicates an expected call of IncrementProgramCounter
func (mr *MockReaderWriterMockRecorder) IncrementProgramCounter(increment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementProgramCounter", reflect.TypeOf((*MockReaderWriter)(nil).IncrementProgramCounter), increment)
}

// PushProgramCounter mocks base method
func (m *MockReaderWriter) PushProgramCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PushProgramCounter")
}

// PushProgramCounter indicates an expected call of PushProgramCounter
func (mr *MockReaderWriterMockRecorder) PushProgramCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushProgramCounter", reflect.TypeOf((*MockReaderWriter)(nil).PushProgramCounter))
}

// PopProgramCounter mocks base method
func (m *MockReaderWriter) PopProgramCounter() uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PopProgramCounter")
	ret0, _ := ret[0].(uint16)
	return ret0
}

// PopProgramCounter indicates an expected call of PopProgramCounter
func (mr *MockReaderWriterMockRecorder) PopProgramCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PopProgramCounter", reflect.TypeOf((*MockReaderWriter)(nil).PopProgramCounter))
}

// GetRegisterValue mocks base method
func (m *MockReaderWriter) GetRegisterValue(register uint8) uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisterValue", register)
	ret0, _ := ret[0].(uint8)
	return ret0
}

// GetRegisterValue indicates an expected call of GetRegisterValue
func (mr *MockReaderWriterMockRecorder) GetRegisterValue(register interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisterValue", reflect.TypeOf((*MockReaderWriter)(nil).GetRegisterValue), register)
}

// SetRegisterValue mocks base method
func (m *MockReaderWriter) SetRegisterValue(register, value uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRegisterValue", register, value)
}

// SetRegisterValue indicates an expected call of SetRegisterValue
func (mr *MockReaderWriterMockRecorder) SetRegisterValue(register, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegisterValue", reflect.TypeOf((*MockReaderWriter)(nil).SetRegisterValue), register, value)
}

// SetRegisterI mocks base method
func (m *MockReaderWriter) SetRegisterI(value uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRegisterI", value)
}

// SetRegisterI indicates an expected call of SetRegisterI
func (mr *MockReaderWriterMockRecorder) SetRegisterI(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegisterI", reflect.TypeOf((*MockReaderWriter)(nil).SetRegisterI), value)
}

// GetRegisterI mocks base method
func (m *MockReaderWriter) GetRegisterI() uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisterI")
	ret0, _ := ret[0].(uint16)
	return ret0
}

// GetRegisterI indicates an expected call of GetRegisterI
func (mr *MockReaderWriterMockRecorder) GetRegisterI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisterI", reflect.TypeOf((*MockReaderWriter)(nil).GetRegisterI))
}

// SetDelayTimer mocks base method
func (m *MockReaderWriter) SetDelayTimer(value uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDelayTimer", value)
}

// SetDelayTimer indicates an expected call of SetDelayTimer
func (mr *MockReaderWriterMockRecorder) SetDelayTimer(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDelayTimer", reflect.TypeOf((*MockReaderWriter)(nil).SetDelayTimer), value)
}

// GetDelayTimer mocks base method
func (m *MockReaderWriter) GetDelayTimer() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDelayTimer")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// GetDelayTimer indicates an expected call of GetDelayTimer
func (mr *MockReaderWriterMockRecorder) GetDelayTimer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDelayTimer", reflect.TypeOf((*MockReaderWriter)(nil).GetDelayTimer))
}

// SetSoundTimer mocks base method
func (m *MockReaderWriter) SetSoundTimer(value uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSoundTimer", value)
}

// SetSoundTimer indicates an expected call of SetSoundTimer
func (mr *MockReaderWriterMockRecorder) SetSoundTimer(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSoundTimer", reflect.TypeOf((*MockReaderWriter)(nil).SetSoundTimer), value)
}

// GetSoundTimer mocks base method
func (m *MockReaderWriter) GetSoundTimer() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSoundTimer")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// GetSoundTimer indicates an expected call of GetSoundTimer
func (mr *MockReaderWriterMockRecorder) GetSoundTimer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSoundTimer", reflect.TypeOf((*MockReaderWriter)(nil).GetSoundTimer))
}
