// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/emu/memory/memory.go

// Package mock_memory is a generated GoMock package.
package mock_memory

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMemory is a mock of Memory interface
type MockMemory struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryMockRecorder
}

// MockMemoryMockRecorder is the mock recorder for MockMemory
type MockMemoryMockRecorder struct {
	mock *MockMemory
}

// NewMockMemory creates a new mock instance
func NewMockMemory(ctrl *gomock.Controller) *MockMemory {
	mock := &MockMemory{ctrl: ctrl}
	mock.recorder = &MockMemoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMemory) EXPECT() *MockMemoryMockRecorder {
	return m.recorder
}

// ReadValue mocks base method
func (m *MockMemory) ReadValue(addr uint16) uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadValue", addr)
	ret0, _ := ret[0].(uint8)
	return ret0
}

// ReadValue indicates an expected call of ReadValue
func (mr *MockMemoryMockRecorder) ReadValue(addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadValue", reflect.TypeOf((*MockMemory)(nil).ReadValue), addr)
}

// WriteValue mocks base method
func (m *MockMemory) WriteValue(addr uint16, value uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WriteValue", addr, value)
}

// WriteValue indicates an expected call of WriteValue
func (mr *MockMemoryMockRecorder) WriteValue(addr, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteValue", reflect.TypeOf((*MockMemory)(nil).WriteValue), addr, value)
}

// ReadNBytes mocks base method
func (m *MockMemory) ReadNBytes(start uint16, n uint8) []uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadNBytes", start, n)
	ret0, _ := ret[0].([]uint8)
	return ret0
}

// ReadNBytes indicates an expected call of ReadNBytes
func (mr *MockMemoryMockRecorder) ReadNBytes(start, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadNBytes", reflect.TypeOf((*MockMemory)(nil).ReadNBytes), start, n)
}

// GetHexDigitAddress mocks base method
func (m *MockMemory) GetHexDigitAddress(digit uint8) uint16 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHexDigitAddress", digit)
	ret0, _ := ret[0].(uint16)
	return ret0
}

// GetHexDigitAddress indicates an expected call of GetHexDigitAddress
func (mr *MockMemoryMockRecorder) GetHexDigitAddress(digit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHexDigitAddress", reflect.TypeOf((*MockMemory)(nil).GetHexDigitAddress), digit)
}
